name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.17.0'
        otp-version: '27.0'

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: mix local
      run: |
        mix local.rebar --force
        mix local.hex --force

    - name: mix compile
      run: |
        mix deps.get
        mix deps.compile
        mix compile
      if: steps.mix-cache.outputs.cache-hit != 'true'

    - name: mix checks
      run: |
        mix deps.unlock --check-unused
        mix format --check-formatted

    - name: mix tests
      run: mix test

